name: Deploy
on:
  pull_request:
    types:
      - closed
    #paths:
    #  - 'group_vars/**'
    #  - 'templates/lambda_function.py.j2'

jobs:
  deploy:
    #if: ${{ github.ref == 'refs/heads/main' && github.repository_owner == 'galaxyproject' }}
    if: github.event.pull_request.merged == true
    name: Deploy rewrite function
    runs-on: ubuntu-latest
    #needs: check
    steps:

      - uses: actions/checkout@v2

      - name: Run deploy
        run: echo ansible-playbook -i hosts deploy.yaml
