name: Deploy
on:
  pull_request:
    types:
      - closed
    paths:
      - 'group_vars/**'
      - 'templates/lambda_function.py.j2'

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

  deploy:
    #if: ${{ github.ref == 'refs/heads/main' && github.repository_owner == 'galaxyproject' }}
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/breakme'
    name: Deploy rewrite function
    runs-on: ubuntu-latest
    #needs: check
    steps:

      - uses: actions/checkout@v2

      - name: Run deploy
        run: echo ansible-playbook -i hosts deploy.yaml
